### ISSUE TITLE
Untranslated English section in https://github.com/MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer.ja-jp/blob/main/Instructions/Labs/LAB_AK_13-deploy-and-debug-custom-azure-iot-edge-module.md

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer.ja-jp#3]
# Module: 
## Lab/Demo: 13
Exercise 4
#### Step: 08

Description of issue

Untranslated English section for these 2 lines in this step:

    The `sensorToObjectCountingModule` route is configured to route messages from the `SimulatedTemperatureSensor` (via `/messages/modules/SimulatedTemplaratureSensor/outputs/temperatureOutput`) module to the custom `ObjectCountingModule` module (via `BrokeredEndpoint(\"/modules/ObjectCountingModule/inputs/input1\")"`).

    The `ObjectCountingModuleToIoTHub` route is configured to route messages that are sent out from the custom `ObjectCountingModule` module (via `/messages/modules/SimulatedTemperatureSensor/outputs/temperatureOutput`) to the Azure IoT Hub service (via `$upstream`).

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
Now, translated. Close it.
![image](https://user-images.githubusercontent.com/49666210/184850527-bdca7264-fd3f-41d5-91f3-61705b977ccc.png)
